version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: mongo-seeder
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/cars
    entrypoint: ["sh", "-c", "sleep 5 && node insert.js"]

volumes:
  mongo-data:
